//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 12:21:39 PM IST 
//


package com.decipher.wsdlboot.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complaint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complaint"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pending" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="running" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="resolve" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complaint", propOrder = {
    "pending",
    "running",
    "resolve"
})
public class Complaint {

    protected int pending;
    protected int running;
    protected int resolve;

    /**
     * Gets the value of the pending property.
     * 
     */
    public int getPending() {
        return pending;
    }

    /**
     * Sets the value of the pending property.
     * 
     */
    public void setPending(int value) {
        this.pending = value;
    }

    /**
     * Gets the value of the running property.
     * 
     */
    public int getRunning() {
        return running;
    }

    /**
     * Sets the value of the running property.
     * 
     */
    public void setRunning(int value) {
        this.running = value;
    }

    /**
     * Gets the value of the resolve property.
     * 
     */
    public int getResolve() {
        return resolve;
    }

    /**
     * Sets the value of the resolve property.
     * 
     */
    public void setResolve(int value) {
        this.resolve = value;
    }

}
