//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 12:21:39 PM IST 
//


package com.decipher.wsdlboot.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetPending_QNAME = new QName("http://issuehandling.decipher.com/", "getPending");
    private final static QName _GetPendingResponse_QNAME = new QName("http://issuehandling.decipher.com/", "getPendingResponse");
    private final static QName _GetReslove_QNAME = new QName("http://issuehandling.decipher.com/", "getReslove");
    private final static QName _GetResloveResponse_QNAME = new QName("http://issuehandling.decipher.com/", "getResloveResponse");
    private final static QName _GetRunning_QNAME = new QName("http://issuehandling.decipher.com/", "getRunning");
    private final static QName _GetRunningResponse_QNAME = new QName("http://issuehandling.decipher.com/", "getRunningResponse");
    private final static QName _UpdateComplaints_QNAME = new QName("http://issuehandling.decipher.com/", "updateComplaints");
    private final static QName _UpdateComplaintsResponse_QNAME = new QName("http://issuehandling.decipher.com/", "updateComplaintsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPending }
     * 
     */
    public GetPending createGetPending() {
        return new GetPending();
    }

    /**
     * Create an instance of {@link GetPendingResponse }
     * 
     */
    public GetPendingResponse createGetPendingResponse() {
        return new GetPendingResponse();
    }

    /**
     * Create an instance of {@link GetReslove }
     * 
     */
    public GetReslove createGetReslove() {
        return new GetReslove();
    }

    /**
     * Create an instance of {@link GetResloveResponse }
     *
     */
    public GetResloveResponse createGetResloveResponse() {
        return new GetResloveResponse();
    }

    /**
     * Create an instance of {@link GetRunning }
     *
     */
    public GetRunning createGetRunning() {
        return new GetRunning();
    }

    /**
     * Create an instance of {@link GetRunningResponse }
     *
     */
    public GetRunningResponse createGetRunningResponse() {
        return new GetRunningResponse();
    }

    /**
     * Create an instance of {@link UpdateComplaints }
     *
     */
    public UpdateComplaints createUpdateComplaints() {
        return new UpdateComplaints();
    }

    /**
     * Create an instance of {@link UpdateComplaintsResponse }
     *
     */
    public UpdateComplaintsResponse createUpdateComplaintsResponse() {
        return new UpdateComplaintsResponse();
    }

    /**
     * Create an instance of {@link Complaint }
     *
     */
    public Complaint createComplaint() {
        return new Complaint();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPending }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://issuehandling.decipher.com/", name = "getPending")
    public JAXBElement<GetPending> createGetPending(GetPending value) {
        return new JAXBElement<GetPending>(_GetPending_QNAME, GetPending.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPendingResponse }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://issuehandling.decipher.com/", name = "getPendingResponse")
    public JAXBElement<GetPendingResponse> createGetPendingResponse(GetPendingResponse value) {
        return new JAXBElement<GetPendingResponse>(_GetPendingResponse_QNAME, GetPendingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReslove }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://issuehandling.decipher.com/", name = "getReslove")
    public JAXBElement<GetReslove> createGetReslove(GetReslove value) {
        return new JAXBElement<GetReslove>(_GetReslove_QNAME, GetReslove.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetResloveResponse }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://issuehandling.decipher.com/", name = "getResloveResponse")
    public JAXBElement<GetResloveResponse> createGetResloveResponse(GetResloveResponse value) {
        return new JAXBElement<GetResloveResponse>(_GetResloveResponse_QNAME, GetResloveResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRunning }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://issuehandling.decipher.com/", name = "getRunning")
    public JAXBElement<GetRunning> createGetRunning(GetRunning value) {
        return new JAXBElement<GetRunning>(_GetRunning_QNAME, GetRunning.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRunningResponse }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://issuehandling.decipher.com/", name = "getRunningResponse")
    public JAXBElement<GetRunningResponse> createGetRunningResponse(GetRunningResponse value) {
        return new JAXBElement<GetRunningResponse>(_GetRunningResponse_QNAME, GetRunningResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateComplaints }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://issuehandling.decipher.com/", name = "updateComplaints")
    public JAXBElement<UpdateComplaints> createUpdateComplaints(UpdateComplaints value) {
        return new JAXBElement<UpdateComplaints>(_UpdateComplaints_QNAME, UpdateComplaints.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateComplaintsResponse }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://issuehandling.decipher.com/", name = "updateComplaintsResponse")
    public JAXBElement<UpdateComplaintsResponse> createUpdateComplaintsResponse(UpdateComplaintsResponse value) {
        return new JAXBElement<UpdateComplaintsResponse>(_UpdateComplaintsResponse_QNAME, UpdateComplaintsResponse.class, null, value);
    }

}
