//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 01:17:07 PM IST 
//


package com.company.wsdlboot.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="data"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="order_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="order_Seq" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="order_Number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="request_Licenses" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rLWO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rLNote" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="end_user_FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="end_user_LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="endUserType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="endUserGSM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="endUserGSM2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="endUser_tagID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="buildingNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="goverenate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="wayNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="propertyType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="splitterPort" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="previousStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="categories" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dropCableLength" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="subcontractor" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="supervisor" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="plannedDate" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "data", propOrder = {

})
public class Data {

    @XmlElement(name = "order_type", required = true)
    protected String orderType;
    @XmlElement(name = "order_Seq", required = true)
    protected String orderSeq;
    @XmlElement(name = "order_Number", required = true)
    protected String orderNumber;
    @XmlElement(name = "request_Licenses", required = true)
    protected String requestLicenses;
    @XmlElement(name = "rLWO", required = true)
    protected String rlwo;
    @XmlElement(name = "rLNote", required = true)
    protected String rlNote;
    @XmlElement(name = "end_user_FirstName", required = true)
    protected String endUserFirstName;
    @XmlElement(name = "end_user_LastName", required = true)
    protected String endUserLastName;
    @XmlElement(required = true)
    protected String creationDate;
    @XmlElement(required = true)
    protected String endUserType;
    @XmlElement(required = true)
    protected String endUserGSM;
    @XmlElement(required = true)
    protected String endUserGSM2;
    @XmlElement(name = "endUser_tagID", required = true)
    protected String endUserTagID;
    @XmlElement(required = true)
    protected String buildingNo;
    @XmlElement(required = true)
    protected String goverenate;
    @XmlElement(required = true)
    protected String area;
    @XmlElement(required = true)
    protected String wayNumber;
    @XmlElement(required = true)
    protected String propertyType;
    @XmlElement(required = true)
    protected String splitterPort;
    @XmlElement(required = true)
    protected String previousStatus;
    @XmlElement(required = true)
    protected String categories;
    @XmlElement(required = true)
    protected String dropCableLength;
    @XmlElement(required = true)
    protected byte[] status;
    @XmlElement(required = true)
    protected byte[] subcontractor;
    @XmlElement(required = true)
    protected byte[] supervisor;
    @XmlElement(required = true)
    protected byte[] plannedDate;

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the orderSeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderSeq() {
        return orderSeq;
    }

    /**
     * Sets the value of the orderSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderSeq(String value) {
        this.orderSeq = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNumber(String value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the requestLicenses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestLicenses() {
        return requestLicenses;
    }

    /**
     * Sets the value of the requestLicenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestLicenses(String value) {
        this.requestLicenses = value;
    }

    /**
     * Gets the value of the rlwo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRLWO() {
        return rlwo;
    }

    /**
     * Sets the value of the rlwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRLWO(String value) {
        this.rlwo = value;
    }

    /**
     * Gets the value of the rlNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRLNote() {
        return rlNote;
    }

    /**
     * Sets the value of the rlNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRLNote(String value) {
        this.rlNote = value;
    }

    /**
     * Gets the value of the endUserFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserFirstName() {
        return endUserFirstName;
    }

    /**
     * Sets the value of the endUserFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserFirstName(String value) {
        this.endUserFirstName = value;
    }

    /**
     * Gets the value of the endUserLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserLastName() {
        return endUserLastName;
    }

    /**
     * Sets the value of the endUserLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserLastName(String value) {
        this.endUserLastName = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the endUserType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserType() {
        return endUserType;
    }

    /**
     * Sets the value of the endUserType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserType(String value) {
        this.endUserType = value;
    }

    /**
     * Gets the value of the endUserGSM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserGSM() {
        return endUserGSM;
    }

    /**
     * Sets the value of the endUserGSM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserGSM(String value) {
        this.endUserGSM = value;
    }

    /**
     * Gets the value of the endUserGSM2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserGSM2() {
        return endUserGSM2;
    }

    /**
     * Sets the value of the endUserGSM2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserGSM2(String value) {
        this.endUserGSM2 = value;
    }

    /**
     * Gets the value of the endUserTagID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserTagID() {
        return endUserTagID;
    }

    /**
     * Sets the value of the endUserTagID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserTagID(String value) {
        this.endUserTagID = value;
    }

    /**
     * Gets the value of the buildingNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingNo() {
        return buildingNo;
    }

    /**
     * Sets the value of the buildingNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingNo(String value) {
        this.buildingNo = value;
    }

    /**
     * Gets the value of the goverenate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoverenate() {
        return goverenate;
    }

    /**
     * Sets the value of the goverenate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoverenate(String value) {
        this.goverenate = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArea(String value) {
        this.area = value;
    }

    /**
     * Gets the value of the wayNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWayNumber() {
        return wayNumber;
    }

    /**
     * Sets the value of the wayNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWayNumber(String value) {
        this.wayNumber = value;
    }

    /**
     * Gets the value of the propertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * Sets the value of the propertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyType(String value) {
        this.propertyType = value;
    }

    /**
     * Gets the value of the splitterPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSplitterPort() {
        return splitterPort;
    }

    /**
     * Sets the value of the splitterPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSplitterPort(String value) {
        this.splitterPort = value;
    }

    /**
     * Gets the value of the previousStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousStatus() {
        return previousStatus;
    }

    /**
     * Sets the value of the previousStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousStatus(String value) {
        this.previousStatus = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategories(String value) {
        this.categories = value;
    }

    /**
     * Gets the value of the dropCableLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropCableLength() {
        return dropCableLength;
    }

    /**
     * Sets the value of the dropCableLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropCableLength(String value) {
        this.dropCableLength = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setStatus(byte[] value) {
        this.status = value;
    }

    /**
     * Gets the value of the subcontractor property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSubcontractor() {
        return subcontractor;
    }

    /**
     * Sets the value of the subcontractor property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSubcontractor(byte[] value) {
        this.subcontractor = value;
    }

    /**
     * Gets the value of the supervisor property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSupervisor() {
        return supervisor;
    }

    /**
     * Sets the value of the supervisor property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSupervisor(byte[] value) {
        this.supervisor = value;
    }

    /**
     * Gets the value of the plannedDate property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPlannedDate() {
        return plannedDate;
    }

    /**
     * Sets the value of the plannedDate property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPlannedDate(byte[] value) {
        this.plannedDate = value;
    }

}
