//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 01:17:07 PM IST 
//


package com.company.wsdlboot.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateOrderStatusRequest }
     * 
     */
    public UpdateOrderStatusRequest createUpdateOrderStatusRequest() {
        return new UpdateOrderStatusRequest();
    }

    /**
     * Create an instance of {@link Usercredentials }
     * 
     */
    public Usercredentials createUsercredentials() {
        return new Usercredentials();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link UpdateOrderStatusResponse }
     * 
     */
    public UpdateOrderStatusResponse createUpdateOrderStatusResponse() {
        return new UpdateOrderStatusResponse();
    }

    /**
     * Create an instance of {@link WFMUpdateWORequest }
     * 
     */
    public WFMUpdateWORequest createWFMUpdateWORequest() {
        return new WFMUpdateWORequest();
    }

    /**
     * Create an instance of {@link WFMUpdateWOResponse }
     * 
     */
    public WFMUpdateWOResponse createWFMUpdateWOResponse() {
        return new WFMUpdateWOResponse();
    }

    /**
     * Create an instance of {@link WFMUpdateStatusRequest }
     * 
     */
    public WFMUpdateStatusRequest createWFMUpdateStatusRequest() {
        return new WFMUpdateStatusRequest();
    }

    /**
     * Create an instance of {@link WFMUpdateStatusResponse }
     * 
     */
    public WFMUpdateStatusResponse createWFMUpdateStatusResponse() {
        return new WFMUpdateStatusResponse();
    }

    /**
     * Create an instance of {@link WFMCreateWORequest }
     * 
     */
    public WFMCreateWORequest createWFMCreateWORequest() {
        return new WFMCreateWORequest();
    }

    /**
     * Create an instance of {@link WFMCreateWOResponse }
     * 
     */
    public WFMCreateWOResponse createWFMCreateWOResponse() {
        return new WFMCreateWOResponse();
    }

}
