//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 01:17:07 PM IST 
//


package com.company.wsdlboot.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="usercredentials" type="{urn:order}usercredentials"/&gt;
 *         &lt;element name="data" type="{urn:order}data"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usercredentials",
    "data"
})
@XmlRootElement(name = "WFMUpdateStatusRequest")
public class WFMUpdateStatusRequest {

    @XmlElement(required = true)
    protected Usercredentials usercredentials;
    @XmlElement(required = true)
    protected Data data;

    /**
     * Gets the value of the usercredentials property.
     *
     * @return
     *     possible object is
     *     {@link Usercredentials }
     *
     */
    public Usercredentials getUsercredentials() {
        return usercredentials;
    }

    /**
     * Sets the value of the usercredentials property.
     *
     * @param value
     *     allowed object is
     *     {@link Usercredentials }
     *
     */
    public void setUsercredentials(Usercredentials value) {
        this.usercredentials = value;
    }

    /**
     * Gets the value of the data property.
     *
     * @return
     *     possible object is
     *     {@link Data }
     *
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     *
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setData(Data value) {
        this.data = value;
    }

}
